# default configuration options for all environments
default:
  # Outgoing emails configuration (see examples above)
  email_delivery:
    delivery_method: $DELIVERY_METHOD
    smtp_settings:
      address: $ADDRESS
      port: $PORT
  attachments_storage_path:
  autologin_cookie_name:
  autologin_cookie_path:
  autologin_cookie_secure:


  scm_subversion_command:
  scm_mercurial_command:
  scm_git_command:
  scm_cvs_command:
  scm_bazaar_command:
  scm_darcs_command:

  scm_stderr_log_file:
  database_cipher_key:
  rmagick_font_path:

production:

development:
